apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: hostpath
spec:
  secretsName: my-cluster-secrets
  sslSecretName: some-name-ssl
  pxc:
    size: 3
    image: -pxc
    volumeSpec:
      hostPath:
        path: /run/data-dir
        type: Directory
  proxysql:
    enabled: true
    size: 1
    image: -proxysql
    volumeSpec:
      hostPath:
        path: /run/proxy-dir
        type: Directory
  pmm:
    enabled: false
